version: '3.9'
services:
  nest_api:
    container_name: nest_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    networks:
      - internal

  react_app:
    container_name: react_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    volumes:
      - ~/resources/certs/:/etc/letsencrypt/
      - ~/resources/www/:/usr/share/nginx/html/
    ports:
      - '80:80'
    networks:
      - internal

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ~/resources/certs/:/etc/letsencrypt/
  #     - ~/resources/html/:/usr/share/nginx/html/

networks:
  internal:
