version: '3.9'
services:
  nest_api:
    container_name: nest_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-api
    networks:
      - internal

  react_app:
    container_name: react_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-webapp
    ports:
      - '80:80'
    networks:
      - internal

networks:
  internal:
