version: '3.9'
services:
  api:
    container_name: genealogy-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    profiles:
      - runner
      - main
    networks:
      - main

  proxy:
    container_name: genealogy-proxy
    restart: unless-stopped
    build:
      context: .
      dockerfile: proxy/Dockerfile
    profiles:
      - runner
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/volumes/dist:/usr/share/nginx/html
      - ~/volumes/certs:/etc/nginx/ssl
    networks:
      - main

  certbot:
    image: certbot/certbot:arm64v8-latest
    profiles:
      - cert
    volumes:
      - ~/volumes/dist:/usr/share/nginx/html
      - ~/volumes/certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path /usr/share/nginx/html/ --force-renewal --agree-tos --quiet -m vuchuc781999@gmail.com -d family-tree.ddns.net
networks:
  main:
