name: Deployment

on:
  push:
    branches: [master]

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d

  deploy-api:
    needs: check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v14.3
        id: changed-files
      - if: contains(steps.changed-files.outputs.all_changed_files, 'apps/api/')
        run: docker-compose up --build --force-recreate --no-deps -d nest_api

  deploy-webapp:
    needs: check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v14.3
        id: changed-files
      - if: contains(steps.changed-files.outputs.all_changed_files, 'apps/webapp/')
        run: docker-compose up --build --force-recreate --no-deps -d react_app

  clear:
    if: ${{ always() }}
    needs: [deploy-api, deploy-webapp]
    runs-on: self-hosted
    steps:
      - run: docker system prune -af
