name: Renew certificates

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

jobs:
  renew-certs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose run --rm certbot certonly --webroot --webroot-path /usr/share/nginx/html/ --force-renewal --agree-tos --quiet -m vuchuc781999@gmail.com -d family-tree.ddns.net
