name: Renew certificates

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  renew-certs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up --force-recreate --no-deps -d certbot
      - run: docker-compose restart proxy

  clean-up:
    if: ${{ always() }}
    needs: [renew-certs]
    runs-on: self-hosted
    steps:
      - run: docker system prune -af
